# Generated by Django 4.1 on 2022-11-05 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0009_alter_store_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(verbose_name='Número do orçamento')),
                ('certificate', models.CharField(default=uuid.UUID('b8ca1af0-57cf-4d97-8c67-68ef315da778'), max_length=255, verbose_name='Certificado')),
                ('emissionDate', models.DateTimeField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('validity', models.DateField(verbose_name='Data de validade')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Subtotal')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Desconto')),
                ('status', models.CharField(choices=[('1', 'Em Negociação'), ('2', 'Em Produção'), ('3', 'Recusado'), ('4', 'Concluído')], default='1', max_length=50)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.store', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçmentos',
            },
        ),
    ]
