# Generated by Django 4.1 on 2022-11-06 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterField(
            model_name='budget',
            name='certificate',
            field=models.CharField(default=uuid.UUID('538ebffb-bdc4-42ab-9266-373693ee9f33'), max_length=255, verbose_name='Certificado'),
        ),
    ]
