# Generated by Django 4.1 on 2022-11-06 15:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_budget_options_alter_budget_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='certificate',
            field=models.CharField(default=uuid.UUID('2cf8b4de-7ad9-4561-80ce-41d7d779fdea'), max_length=255, verbose_name='Certificado'),
        ),
    ]
