# Generated by Django 4.1 on 2022-11-08 01:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_budget_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='certificate',
            field=models.CharField(default=uuid.UUID('32e6feec-b960-4409-9196-e8d2429d4fd5'), max_length=255, verbose_name='Certificado'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('measurement', models.CharField(choices=[('1', 'UN'), ('2', 'CX'), ('3', 'L'), ('4', 'Centro'), ('5', 'GALÃO'), ('6', 'KG'), ('7', 'JG'), ('8', 'M'), ('9', 'PC'), ('10', 'PR'), ('11', 'BR')], max_length=50)),
                ('quantity', models.FloatField(verbose_name='Quantidade')),
                ('unityValue', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Unitário')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Total')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='budget.budget')),
            ],
            options={
                'verbose_name': 'Produto - Orçamento',
                'verbose_name_plural': 'Produtos - Orçamentos',
            },
        ),
    ]
