# Generated by Django 4.1 on 2022-10-26 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=255, null=True)),
                ('brandName', models.CharField(max_length=255)),
                ('corporateName', models.CharField(max_length=255)),
                ('document', models.CharField(max_length=100, unique=True)),
                ('ie', models.CharField(max_length=100, null=True, unique=True)),
                ('postalCode', models.CharField(max_length=255)),
            ],
        ),
    ]
