# Generated by Django 4.1 on 2022-10-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_cellphone_store_city_store_email_store_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', max_length=50),
        ),
    ]
