# Generated by Django 4.1 on 2022-11-04 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0005_remove_store_japones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
        migrations.RemoveField(
            model_name='store',
            name='password',
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
