# Generated by Django 4.1 on 2022-11-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_store_cellphone_alter_store_ie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': 'Loja', 'verbose_name_plural': 'Lojas'},
        ),
    ]
