# Generated by Django 4.1 on 2022-11-05 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0008_alter_store_cellphone_alter_store_ie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('corporateName', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('document', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='CPF/CNPJ')),
                ('ie', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='IE')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefone')),
                ('cellPhone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Celular')),
                ('email', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='E-mail')),
                ('postalCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='CEP')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernanbuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, null=True, verbose_name='Estado')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cidade')),
                ('district', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bairro')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número')),
                ('observation', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('1', 'Ativo'), ('2', 'Inativo')], default='1', max_length=50)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.store', verbose_name='Loja')),
            ],
        ),
    ]
